### ISSUE TITLE
Function to collect all form data

### ISSUE THREAD

**Issue by binarykitchen** [TheLudd/react-form-data#3]
Would be great to have a function that returns a map of name + value regardless whether they have changed or not. Because I need that for RESTful operations. Thanks!

**Comment by TheLudd** [comment]
Why not just use `this.formData`?

**Comment by binarykitchen** [comment]
it only contains those which have changed

**Comment by TheLudd** [comment]
But if you need to initialize the data object with any other data than an empty object you should implement `getInitialFormData`. Will this not solve your problem?

**Comment by binarykitchen** [comment]
yes, i know, i could use `getInitialFormData` but IMO this is redundant. i am already initializing the input fields with values, so why not traverse through them all and automatically initialize form data?

**Comment by TheLudd** [comment]
There is no way (I know of) to just pick up values from arbitrary fields in the form. The thing about react-form-data is that you just assign names to the input fields and the onChange events will give you the info of what field changed. When I want to initialize a from with data I use the object returned from `getInitialFormData` to  initialize the fields. You can also use `resetFormData` and pass in the data object in order to have non empty initial fields.

**Comment by binarykitchen** [comment]
Right, I realized that and this is unfortunate. Why the need to explicitly pass on initial data when these are already passed on within each single input like `value = ...` ?

Guess, that's one of the React disadvantages?

**Comment by TheLudd** [comment]
I rather think that it is one of Reacts advantages. Yes, sometimes you need to specify things explicitly but I prefer the total control instead of a framework that assumes that things should be done a certain way. There are lots of other frameworks like that =)

Closing this since the situation you are after is solvable with `getInitialFormData`. That method was added to solve this exact situation. There is also this which you might prefer, although I have not used it myself. http://facebook.github.io/react/docs/two-way-binding-helpers.html

**Comment by binarykitchen** [comment]
Right, I am getting the hang of React now ... and two way bindings will make it more ugly. Guess I'll have to invent something for this ... thanks for your good inputs.
