### ISSUE TITLE
Please post whole code ..

### ISSUE THREAD

**Issue by ghost** [TheLudd/react-form-data#6]
Hi there,

I am new to react and javascript currently working on to get the submitted form values as object, while browsing I got below code. @ **//input elements here** here I have used `input type='text'` as showed below, but I am not getting values as object. 

How to display the values (object) in browser console, please help..  

```
var React = require('react');
var FormData = require('react-form-data');
var MyForm = React.createClass({
  mixins: [ FormData ],
  handleSubmit: function() {
     var url = 'urlToSendDataTo';
     myRequestLib.post(url, this.formData);
  },
  render: function() {
    return (
      <form onChange={this.updateFormData} onSubmit={this.handleSubmit}>
        //input elements here
       <lable>Name</label>
       <input type='text' name='sample'>
      </form>
    )
  }
});
```

Thanks,
Shashank

**Comment by TheLudd** [comment]
The code looks right but when you attach an `onSubmit` handler to a form you need to call `preventDefault` on the submit event, otherwise the page will reload. (shown in the example here https://facebook.github.io/react/docs/forms.html#controlled-components)

So change the `handleSubmit` function to

```
  handleSubmit: function(e) {
     e.preventDefault()
     var url = 'urlToSendDataTo';
     myRequestLib.post(url, this.formData);
  }
```
